/turtlesim2/my_turtle:
  ros__parameters:
    background_b: 0
    background_g: 255
    background_r: 0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1500
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false